# Site settings
title: Mike Randrup's Blog
email: github@mikerandrup.com
description: "Pet projects in code, graphics, and more."
baseurl: ""
url: "http://blog.mikerandrup.com"
twitter_username: mikerandrup
github_username:  mikerandrup

# Build settings
markdown: kramdown
permalink: pretty
